### ISSUE TITLE
fix: warning when wrong definitions

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#228]
Looks like we're not warned when a component is badly defined

```
meilisearch:
  image: getmeili/meilisearch
  containerPort: 7700
  probesPath: /healthz # ici identifier la route de health fournie par meilisearch
  env:
     - name: MEILI_MASTER_KEY
       value: masterKey
     - name: MEILI_NO_ANALYTICS
       value :true
```

Here `~chart` is missing and component is not deployed
