### ISSUE TITLE
disable cluster interactions on build 

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#281]
build command should not interact with cluster, just build the manifests from GIT

**Comment by revolunet** [comment]
can be disabled with :

```yaml
dependencies:
  fabrique:
    import: socialgouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        patches:
          rancherProjectId:
            enabled: false
```
