### ISSUE TITLE
sealed-secret validator

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#325]
trying to deploy "dev" environment on some other cluster :

```sh
handleAxiosError is not a function
TypeError: handleAxiosError is not a function
    at verifySecret (/private/var/folders/cj/ndwdv0lx5bq0hbbj6r5dbrf80000gn/T/kontinuous/build-4nBMn1/charts/project/charts/fabrique/charts/contrib/validators/sealed-secrets.js:72:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at module.exports (/private/var/folders/cj/ndwdv0lx5bq0hbbj6r5dbrf80000gn/T/kontinuous/build-4nBMn1/charts/project/charts/fabrique/charts/contrib/validators/sealed-secrets.js:82:19)
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180354:24
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180354:24
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180354:24
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
```

the secrets have been re-sealed locally but looks like error management is broken

One can configure kubeseal endpoint with :
```yaml
projectName: fabrique

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        validators:
          sealedSecrets:
            options:
              clusters:
                dev:
                  kubesealEndpoint: "https://kubeseal.ovh.fabrique.social.gouv.fr"
```
